# Generated by Django 3.0.7 on 2020-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_imagemodel_encoded_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='encoded_string',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
