# Generated by Django 3.0.7 on 2020-06-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20200606_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='updated_at',
        ),
    ]
